kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: nexus-mirror
  annotations:
    openshift.io/image.insecureRepository: "true"
    openshift.io/display-name: Nexus
    openshift.io/provider-display-name: Nexus
spec:
  tags:
    - name: "latest"
      annotations:
        description: Nexus image.
        iconClass: icon-jboss
        tags: nexus
        supports: xpaas:1.4
        version: "latest"
      from:
        kind: DockerImage
        name: quay.io/jschwan/rhpam-testing-nexus
      importPolicy:
        insecure: true
      referencePolicy:
        type: Local
